version: 7
profiles: []
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - ⌘-C
    - Ctrl-C
  paste:
    - ⌘-V
    - Ctrl-V
  select-all:
    - ⌘-A
    - Ctrl-A
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  home:
    - Home
  end:
    - End
  previous-word:
    - ⌘-Left
    - Ctrl-Left
  next-word:
    - ⌘-Right
    - Ctrl-Right
  delete-previous-word:
    - ⌘-Backspace
    - Ctrl-Backspace
  delete-line: []
  delete-next-word:
    - ⌘-Delete
    - Ctrl-Delete
  search:
    - ⌘-F
    - Ctrl-F
  pane-focus-all:
    - ⌘-Shift-I
    - Ctrl-Shift-I
  focus-all-tabs:
    - ⌘-⌥-Shift-I
    - Ctrl-⌥-Shift-I
  scroll-to-top:
    - Shift-PageUp
  scroll-up: null
  scroll-down: null
  scroll-to-bottom:
    - Shift-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - ⌘-,
    - Ctrl-,
  serial: []
  restart-serial-session: []
  new-tab:
    - ⌘-N
    - Ctrl-N
  new-window: []
  profile: {}
  profile-selectors: {}
  toggle-fullscreen: []
  close-tab:
    - ⌘-W
    - Ctrl-W
  reopen-tab:
    - ⌘-Shift-T
    - Ctrl-Shift-T
  toggle-last-tab: []
  rename-tab: []
  next-tab:
    - ⌥-Right
    - Alt-Right
  previous-tab:
    - ⌥-Left
    - Alt-Left
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  tab-1:
    - ⌘-1
    - Ctrl-1
  tab-2:
    - ⌘-2
    - Ctrl-2
  tab-3:
    - ⌘-3
    - Ctrl-3
  tab-4:
    - ⌘-4
    - Ctrl-4
  tab-5:
    - ⌘-5
    - Ctrl-5
  tab-6:
    - ⌘-6
    - Ctrl-6
  tab-7:
    - ⌘-7
    - Ctrl-7
  tab-8:
    - ⌘-8
    - Ctrl-8
  tab-9:
    - ⌘-9
    - Ctrl-9
  tab-10: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab: []
  combine-tabs: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right: []
  split-bottom: []
  split-left: []
  split-top: []
  pane-nav-right: []
  pane-nav-down: []
  pane-nav-up: []
  pane-nav-left: []
  pane-nav-previous: []
  pane-nav-next: []
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize: []
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector: []
  switch-profile: []
  command-selector:
    - ⌘-Shift-P
    - Ctrl-Shift-P
  clear:
    - ⌘-K
    - Ctrl-K
  copy: []
terminal:
  searchOptions: {}
  colorScheme:
    name: One Dark
    foreground: '#ABB2BF'
    background: '#282c34'
    cursor: '#ABB2BF'
    colors:
      - '#383a42'
      - '#e45649'
      - '#50a14f'
      - '#c18401'
      - '#0184bc'
      - '#a626a4'
      - '#0997b3'
      - '#fafafa'
      - '#383a42'
      - '#e45649'
      - '#50a14f'
      - '#c18401'
      - '#0184bc'
      - '#a626a4'
      - '#0997b3'
      - '#fafafa'
    selection: '#3e4451'
  font: CaskaydiaCove Nerd Font
  cursor: beam
  customColorSchemes:
    - name: One Dark
      foreground: '#ABB2BF'
      background: '#282c34'
      cursor: '#ABB2BF'
      colors:
        - '#383a42'
        - '#e45649'
        - '#50a14f'
        - '#c18401'
        - '#0184bc'
        - '#a626a4'
        - '#0997b3'
        - '#fafafa'
        - '#383a42'
        - '#e45649'
        - '#50a14f'
        - '#c18401'
        - '#0184bc'
        - '#a626a4'
        - '#0997b3'
        - '#fafafa'
      selection: '#3e4451'
  copyAsHTML: false
  hideTabIndex: true
  fontSize: 12
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  sixel: false
ssh: {}
clickableLinks: {}
accessibility: {}
appearance:
  flexTabs: true
  css: ''
  frame: native
  spaciness: 0.9
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableWelcomeTab: false
pluginBlacklist:
  - ssh
  - telnet
  - serial
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
docker: {}
recoverTabs: false
