notARepository: quit

git:
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  log:
    order: topo-order
    showGraph: when-maximised
  disableForcePushing: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName} --}
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
  paging:
    colorArg: always
    useConfig: true

update:
  method: never

gui:
  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  mouseEvents: true
  sidePanelWidth: 0.3333
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  language: "en"
  timeFormat: "02 Jan 06"
  shortTimeFormat: "3:04PM"
  showListFooter: true
  showFileTree: true
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  showFileIcons: true
  commandLogSize: 8
  splitDiff: auto
  border: single
  animateExplosion: true
  portraitMode: auto
  nerdFontsVersion: "3"

os:
  editPreset: "vscode"
