notARepository: quit

git:
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  log:
    order: topo-order
    showGraph: when-maximised
  disableForcePushing: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName} --}
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium

  paging:
    pager: delta --dark --paging=never

update:
  method: never

gui:
  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  mouseEvents: true
  sidePanelWidth: 0.3333
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  language: "en"
  timeFormat: "02 Jan 06"
  shortTimeFormat: "3:04PM"
  showListFooter: true
  showFileTree: true
  showRandomTip: false
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  commandLogSize: 0
  splitDiff: auto
  border: single
  animateExplosion: true
  portraitMode: auto
  nerdFontsVersion: "2"
  showFileIcons: true

keybinding:
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    findBaseCommitForFixup: "<c-f>"
    confirmDiscard: "x"
    ignoreFile: "i"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
    toggleTreeView: "`"
    openMergeTool: "M"
    openStatusFilter: "<c-b>"
    copyFileInfoToClipboard: "y"
  main:
    toggleSelectHunk: a
    pickBothHunks: b
    editSelectHunk: E
  universal:
    quit: "q"
    quit-alt1: <c-c>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: ","
    nextPage: .
    scrollLeft: H
    scrollRight: L
    gotoTop: "<"
    gotoBottom: ">"
    toggleRangeSelect: "v"
    rangeSelectDown: <s-down>
    rangeSelectUp: <s-up>
    prevBlock: ""
    nextBlock: ""
    prevBlock-alt: h
    nextBlock-alt: l
    nextBlock-alt2: <tab>
    prevBlock-alt2: <backtab>
    nextMatch: n
    prevMatch: N
    startSearch: /
    optionMenu: <disabled>
    optionMenu-alt1: "?"
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirmInEditor: <a-enter>
    remove: d
    new: n
    edit: e
    openFile: o
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    scrollUpMain-alt2: <c-u>
    scrollDownMain-alt2: <c-d>
    executeCustomCommand: ":"
    createRebaseOptionsMenu: "m"
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: <right>
    prevTab: <left>
    nextScreenMode: +
    prevScreenMode: _
    undo: z
    redo: <c-z>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-r>
    submitEditorText: <enter>
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
    openDiffTool: <c-t>
